# action.yml
name: 'AWS eb cli command'

author: BeOp

description: 'Provide eb cli commands'

branding:
  icon: 'terminal'  
  color: 'white'
  
inputs:
  command:  # id of input
    description: '<command>'
    required: true
    default: 'deploy'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
